baseURL = '/'
languageCode = 'en-us'
title = 'Read This'
enableGitInfo = true

[params]
brand = "Read This"
description = "My personal collection of helpful tidbits, basic tutorials, and personal posts."
dark_mode = true
front_page_content = ["guides", "posts"]
menu = [
    { Name = "Guides", URL = "/guides/", HasChildren = true, Limit = 5 },
    { Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 15 },
    { Name = "Pinned", URL = "/pinned/", HasChildren = true, Limit = 15 },
    { Name = "Benchmarks", URL = "/benchmarks/", HasChildren = false },
    { Name = "Unfiltered Rants", URL = "/unfiltered-rants/", HasChildren = false },
    { Name = "About", URL = "/about/", HasChildren = false },
]

[markup.highlight]
style = 'catppuccin-macchiato'

[[module.imports]]
path = "github.com/martignoni/hugo-notice"
